env: "mpe"

env_args:
  key: "simple_tag_0vis_colli"
  map_name: "prey_predator"
  num_predators: 10
  num_agents: 10
  predator_size: 0.04
  predator_accel: 5.0
  num_preys: 5
  prey_size: 0.05
  prey_accel: 7.0
  num_landmarks: 2
  time_limit: 60
  individual_reward: False
  reward_discrete: False
  reward_rendundant: False # original reward function
  prey_wrapper: "PretrainedTag"
  visibility_range: 2
  shape: True

common_reward: True

#logs 
use_tensorboard: True
test_greedy: True
test_nepisode: 32
test_interval: 25000
log_interval: 25000
runner_log_interval: 25000
learner_log_interval: 25000

save_model: True # Save the models to disk
save_model_type: "latest"
save_model_interval: 25000 # Save models after this many timesteps

t_max: 10050000

checkpoint_path: "" # Load a checkpoint from this path, such as results/models/prey_predator_test/research_seed499_2026-01-08_21-10-52
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
save_animation: False

scale_cf: 100.0
weight_ir: 1
weight_cs: 5.0