env: hallway

env_args:
  key: simple
  map_name: 'hallway'
  n_agents: 3
  n_groups: 1
  state_numbers: [3, 6, 9]
  group_ids: [0, 0, 0]
  reward_win: 10
  obs_last_action: False
  state_last_action: False
  
common_reward: True

#logs 
use_tensorboard: True
test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000

save_model: True # Save the models to disk
save_model_type: "latest"
save_model_interval: 50000 # Save models after this many timesteps

t_max: 2050000

checkpoint_path: "" # Load a checkpoint from this path, such as results/models/pp_9a3g_rule/i2cp_spatio_seed37_pp_9a3g_rule_2025-05-21_23-31-32
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
save_animation: False

scale_cf: 100.0
weight_ir: 2
weight_cs: 0.5